devices([
  "iPhone 17 Pro Max",
  "iPhone 11 Pro Max",
  "iPad Pro 13-inch (M4)",
])

languages([
  "en-US",
  "de-DE",
  "ja",
  "ru",
  "zh-Hans",
])

scheme("Screenshots")
workspace("MensaDresden.xcworkspace")
output_directory("./appstore_screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
launch_arguments(["--uitesting"])
